version: '3.7'
services:
    php:
        image: php:7.4-fpm   
        volumes:
            - ./www:/usr/share/nginx/html
    nginx:
        image: nginx:1.17.8
        ports:
            - 80:80
        volumes:
            - ./www:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
    mysql:
        image: mysql
        volumes:
            - ./database/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: myusername
            MYSQL_PASSWORD: mypassword
            MYSQL_DATABASE: mydatabase
    pma:
        image: phpmyadmin/phpmyadmin
        ports: 
            - 8080:80
        links:
            - mysql:db
     