version: '3.7'
services:
    php:
        image: php:7-apache
        ports:
            - 8090:80
        volumes:
            - ./www:/var/www/html
    mysql:
        image: mysql
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: myusername
            MYSQL_PASSWORD: mypassword
            MYSQL_DATABASE: mydatabase
    pma:
        image: phpmyadmin/phpmyadmin
        ports: 
            - 8080:80
        links:
            - mysql:db
     